apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repo-target
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph
